### ISSUE TITLE
flarum.ERROR: InvalidArgumentException: No hint path defined for [fof-subscribed]

### ISSUE THREAD

**Issue by ghost** [FriendsOfFlarum/subscribed#10]
```
[2020-11-15 15:57:44] flarum.ERROR: InvalidArgumentException: No hint path defined for [fof-subscribed]. in /var/www/html/flarum/vendor/illuminate/view/FileViewFinder.php:112
Stack trace:
#0 /var/www/html/flarum/vendor/illuminate/view/FileViewFinder.php(90): Illuminate\View\FileViewFinder->parseNamespaceSegments()
#1 /var/www/html/flarum/vendor/illuminate/view/FileViewFinder.php(76): Illuminate\View\FileViewFinder->findNamespacedView()
#2 /var/www/html/flarum/vendor/illuminate/view/Factory.php(131): Illuminate\View\FileViewFinder->find()
#3 /var/www/html/flarum/vendor/illuminate/mail/Mailer.php(355): Illuminate\View\Factory->make()
#4 /var/www/html/flarum/vendor/illuminate/mail/Mailer.php(334): Illuminate\Mail\Mailer->renderView()
#5 /var/www/html/flarum/vendor/illuminate/mail/Mailer.php(246): Illuminate\Mail\Mailer->addContent()
#6 /var/www/html/flarum/vendor/flarum/core/src/Notification/NotificationMailer.php(51): Illuminate\Mail\Mailer->send()
#7 /var/www/html/flarum/vendor/flarum/core/src/Notification/Job/SendEmailNotificationJob.php(37): Flarum\Notification\NotificationMailer->send()
#8 /var/www/html/flarum/vendor/illuminate/container/BoundMethod.php(36): Flarum\Notification\Job\SendEmailNotificationJob->handle()
#9 /var/www/html/flarum/vendor/illuminate/container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#10 /var/www/html/flarum/vendor/illuminate/container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#11 /var/www/html/flarum/vendor/illuminate/container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#12 /var/www/html/flarum/vendor/illuminate/container/Container.php(590): Illuminate\Container\BoundMethod::call()
#13 /var/www/html/flarum/vendor/illuminate/bus/Dispatcher.php(94): Illuminate\Container\Container->call()
#14 /var/www/html/flarum/vendor/illuminate/pipeline/Pipeline.php(130): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#15 /var/www/html/flarum/vendor/illuminate/pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /var/www/html/flarum/vendor/illuminate/bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then()
#17 /var/www/html/flarum/vendor/illuminate/queue/CallQueuedHandler.php(83): Illuminate\Bus\Dispatcher->dispatchNow()
#18 /var/www/html/flarum/vendor/illuminate/pipeline/Pipeline.php(130): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#19 /var/www/html/flarum/vendor/illuminate/pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 /var/www/html/flarum/vendor/illuminate/queue/CallQueuedHandler.php(85): Illuminate\Pipeline\Pipeline->then()
#21 /var/www/html/flarum/vendor/illuminate/queue/CallQueuedHandler.php(59): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#22 /var/www/html/flarum/vendor/illuminate/queue/Jobs/Job.php(88): Illuminate\Queue\CallQueuedHandler->call()
#23 /var/www/html/flarum/vendor/illuminate/queue/SyncQueue.php(45): Illuminate\Queue\Jobs\Job->fire()
#24 /var/www/html/flarum/vendor/flarum/core/src/Notification/NotificationSyncer.php(163): Illuminate\Queue\SyncQueue->push()
#25 /var/www/html/flarum/vendor/flarum/core/src/Notification/NotificationSyncer.php(110): Flarum\Notification\NotificationSyncer->mailNotifications()
#26 /var/www/html/flarum/vendor/fof/subscribed/src/Jobs/SendNotificationWhenDiscussionIsStarted.php(55): Flarum\Notification\NotificationSyncer->sync()
#27 /var/www/html/flarum/vendor/illuminate/container/BoundMethod.php(36): FoF\Subscribed\Jobs\SendNotificationWhenDiscussionIsStarted->handle()
#28 /var/www/html/flarum/vendor/illuminate/container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#29 /var/www/html/flarum/vendor/illuminate/container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#30 /var/www/html/flarum/vendor/illuminate/container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#31 /var/www/html/flarum/vendor/illuminate/container/Container.php(590): Illuminate\Container\BoundMethod::call()
#32 /var/www/html/flarum/vendor/illuminate/bus/Dispatcher.php(94): Illuminate\Container\Container->call()
#33 /var/www/html/flarum/vendor/illuminate/pipeline/Pipeline.php(130): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#34 /var/www/html/flarum/vendor/illuminate/pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /var/www/html/flarum/vendor/illuminate/bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then()
#36 /var/www/html/flarum/vendor/illuminate/queue/CallQueuedHandler.php(83): Illuminate\Bus\Dispatcher->dispatchNow()
#37 /var/www/html/flarum/vendor/illuminate/pipeline/Pipeline.php(130): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#38 /var/www/html/flarum/vendor/illuminate/pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /var/www/html/flarum/vendor/illuminate/queue/CallQueuedHandler.php(85): Illuminate\Pipeline\Pipeline->then()
#40 /var/www/html/flarum/vendor/illuminate/queue/CallQueuedHandler.php(59): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#41 /var/www/html/flarum/vendor/illuminate/queue/Jobs/Job.php(88): Illuminate\Queue\CallQueuedHandler->call()
#42 /var/www/html/flarum/vendor/illuminate/queue/SyncQueue.php(45): Illuminate\Queue\Jobs\Job->fire()
#43 /var/www/html/flarum/vendor/fof/subscribed/src/Listeners/DiscussionCreated.php(72): Illuminate\Queue\SyncQueue->push()
#44 /var/www/html/flarum/vendor/illuminate/events/Dispatcher.php(369): FoF\Subscribed\Listeners\DiscussionCreated->whenDiscussionWasStarted()
#45 /var/www/html/flarum/vendor/illuminate/events/Dispatcher.php(218): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#46 /var/www/html/flarum/vendor/flarum/core/src/Foundation/DispatchEventsTrait.php(33): Illuminate\Events\Dispatcher->dispatch()
#47 /var/www/html/flarum/vendor/flarum/core/src/Discussion/Command/StartDiscussionHandler.php(97): Flarum\Discussion\Command\StartDiscussionHandler->dispatchEventsFor()
#48 /var/www/html/flarum/vendor/illuminate/bus/Dispatcher.php(90): Flarum\Discussion\Command\StartDiscussionHandler->handle()
#49 /var/www/html/flarum/vendor/illuminate/pipeline/Pipeline.php(130): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#50 /var/www/html/flarum/vendor/illuminate/pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#51 /var/www/html/flarum/vendor/illuminate/bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then()
#52 /var/www/html/flarum/vendor/illuminate/bus/Dispatcher.php(76): Illuminate\Bus\Dispatcher->dispatchNow()
#53 /var/www/html/flarum/vendor/flarum/core/src/Api/Controller/CreateDiscussionController.php(72): Illuminate\Bus\Dispatcher->dispatch()
#54 /var/www/html/flarum/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(96): Flarum\Api\Controller\CreateDiscussionController->data()
#55 /var/www/html/flarum/vendor/flarum/core/src/Api/Controller/AbstractCreateController.php(22): Flarum\Api\Controller\AbstractSerializeController->handle()
#56 /var/www/html/flarum/vendor/flarum/core/src/Http/RouteHandlerFactory.php(38): Flarum\Api\Controller\AbstractCreateController->handle()
#57 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(65): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#58 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\DispatchRoute->process()
#59 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Laminas\Stratigility\Next->handle()
#60 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\SetLocale->process()
#61 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(45): Laminas\Stratigility\Next->handle()
#62 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\CheckCsrfToken->process()
#63 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(55): Laminas\Stratigility\Next->handle()
#64 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithHeader->process()
#65 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(32): Laminas\Stratigility\Next->handle()
#66 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithSession->process()
#67 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(51): Laminas\Stratigility\Next->handle()
#68 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\RememberFromCookie->process()
#69 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#70 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\StartSession->process()
#71 /var/www/html/flarum/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle()
#72 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Api\Middleware\FakeHttpMethods->process()
#73 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#74 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ParseJsonBody->process()
#75 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#76 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\HandleErrors->process()
#77 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#78 /var/www/html/flarum/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#79 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\RequestHandler->process()
#80 /var/www/html/flarum/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Laminas\Stratigility\Next->handle()
#81 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePathRouter->process()
#82 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(42): Laminas\Stratigility\Next->handle()
#83 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\OriginalMessages->process()
#84 /var/www/html/flarum/vendor/middlewares/base-path/src/BasePath.php(53): Laminas\Stratigility\Next->handle()
#85 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePath->process()
#86 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#87 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73): Laminas\Stratigility\MiddlewarePipe->process()
#88 /var/www/html/flarum/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#89 /var/www/html/flarum/vendor/flarum/core/src/Http/Server.php(42): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#90 /var/www/html/flarum/index.php(26): Flarum\Http\Server->listen()
#91 {main}  
```

```
# php flarum info
Flarum core 0.1.0-beta.14.1
PHP version: 7.4.12
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mysqlnd, PDO, Phar, SimpleXML, sockets, sqlite3, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, xmlreader, zip
+---------------------------------+------------------+--------+
| Flarum Extensions               |                  |        |
+---------------------------------+------------------+--------+
| ID                              | Version          | Commit |
+---------------------------------+------------------+--------+
| flarum-approval                 | v0.1.0-beta.14   |        |
| flarum-bbcode                   | v0.1.0-beta.12   |        |
| flarum-emoji                    | v0.1.0-beta.14   |        |
| flarum-flags                    | v0.1.0-beta.14.1 |        |
| flarum-likes                    | v0.1.0-beta.14   |        |
| flarum-lock                     | v0.1.0-beta.14   |        |
| flarum-markdown                 | v0.1.0-beta.14   |        |
| flarum-mentions                 | v0.1.0-beta.14   |        |
| flarum-sticky                   | v0.1.0-beta.14   |        |
| flarum-subscriptions            | v0.1.0-beta.14   |        |
| flarum-suspend                  | v0.1.0-beta.14   |        |
| flarum-tags                     | v0.1.0-beta.14   |        |
| flarum-lang-english             | v0.1.0-beta.14.1 |        |
| flarum-statistics               | v0.1.0-beta.14   |        |
| fof-user-bio                    | 0.3.1            |        |
| tolgaaaltas-lang-turkish        | 0.14.1           |        |
| v17development-seo              | 1.4              |        |
| fof-follow-tags                 | 0.5.1            |        |
| fof-formatting                  | 0.2.0            |        |
| fof-split                       | 0.5.0            |        |
| tolgaaaltas-turkish             | 0.14.0           |        |
| nearata-signup-confirm-password | v2.1.0           |        |
| fof-forum-statistics-widget     | 0.3.0            |        |
| nearata-copy-code-to-clipboard  | v1.1.0           |        |
| fof-drafts                      | 0.2.0            |        |
| fof-best-answer                 | 0.2.0            |        |
| fof-links                       | 0.4.0            |        |
| fof-linguist                    | 0.4.4            |        |
| fof-terms                       | 0.5.0            |        |
| fof-merge-discussions           | 0.4.0            |        |
| fof-spamblock                   | 0.3.0            |        |
| fof-stopforumspam               | 0.3.1            |        |
| fof-geoip                       | 0.2.0            |        |
| fof-ban-ips                     | 0.3.0            |        |
| matteocontrini-imgur-upload     | v3.4.1           |        |
| fof-reactions                   | 0.4.2            |        |
| fof-profile-image-crop          | 0.2.0            |        |
| fof-pages                       | 0.5.0            |        |
| fof-nightmode                   | 0.6.0            |        |
| fof-github-autolink             | 0.1.4            |        |
| kyrne-shout                     | 0.2.4-beta.1     |        |
| clarkwinkelmann-author-change   | 0.2.1            |        |
| fof-filter                      | 0.1.0-beta.3     |        |
| fof-username-request            | 0.3.0            |        |
| nomiscz-auth-steam              | v0.2.0           |        |
| fof-oauth                       | 0.1.0            |        |
| michaelbelgium-discussion-views | v5.0.0           |        |
| michaelbelgium-profile-views    | v4.0.0           |        |
| fof-analytics                   | 0.10.0           |        |
| askvortsov-categories           | v1.1.0           |        |
+---------------------------------+------------------+--------+
Base URL: https://dursuncanpoyraz.com.tr/flarum
Installation path: /var/www/html/flarum
Debug mode: off
```

**Comment by ghost** [comment]
https://github.com/askvortsov1/flarum-moderator-warnings/issues/12
